version: "3.9"
services:
  app:
    image: wasm-demo-mysql-client
    build: 
      context: client-app
    platform: wasi/wasm
    runtime: io.containerd.wasmedge.v1
    environment:
      DB_URL: "mysql://db:3306/mysql"
      DB_PASSWORD: "password"
  db:
    image: wasm-demo-mariadb
    build:
      context: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password" # This is just for an example. Do not use for a production environment.